config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'custom_post_form', to: 'custom_post_form#create', as: 'custom_post_form'
  resources :resources
  resources :local_resources
  resources :feedbacks
  post '/save_answers', to: 'responses#create', as: 'save_answers'
  resources :surveys do
    resources :responses
    member do
      get 'select_language'
    end
  end
  get 'get_questions/:survey_id/:language' , to: 'questions#get_questions', as: :get_questions
  resources :questions
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  root "home#index"

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  get '/show_all_responses', to: 'responses#show_all_responses'
  get '/feedback', to: 'resources#feedback'

  get '/getcounter', to: 'counter#get_counter'
  post '/increment', to: 'counter#increment_counter'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey

  def self.ransackable_attributes(auth_object = nil)
    ["child", "created_at", "id", "language", "option_points_list", "option_selected_to_display_child", "options_list", "parent_question_number", "question_number", "question_text", "survey_id", "updated_at"]
  end

  def options_list= list
    if list.is_a? String
      list = JSON.parse(list)
    end
    super list
  end

  def option_points_list= list
    if list.is_a? String
      list = JSON.parse(list)
    end
    super list
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  # def index
  #   @questions = Question.all
  # end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  # def new
  #   @question = Question.new
  # end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  # def create
  #   @question = Question.new(question_params)

  #   respond_to do |format|
  #     if @question.save
  #       format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
  #       format.json { render :show, status: :created, location: @question }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @question.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /questions/1 or /questions/1.json
  # def update
  #   respond_to do |format|
  #     if @question.update(question_params)
  #       format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
  #       format.json { render :show, status: :ok, location: @question }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @question.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /questions/1 or /questions/1.json
  # def destroy
  #   @question.destroy

  #   respond_to do |format|
  #     format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  def get_questions
    @survey = Survey.find(params[:survey_id])
    @language = params[:language]
    @questions = Question.where(survey_id: params[:survey_id], language: @language)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_question
    #   @question = Question.find(params[:id])
    # end

    # # Only allow a list of trusted parameters through.
    # def question_params
    #   params.fetch(:question, {})
    # end


end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/get_questions.html.erb
<div class="container p-5">
  <div>
    <h1 class="style-colour"><%= @survey.survey_name %></h1>
    <h6 style="text-align: right;color: black;"><i>Language: <%= @language %></i></h6>
  </div>
  <div class="card bg-light p-5">
    <% @questions.each do |question| %>
      <div class="">
        <% if !question.parent_question_number.present? %>
          <div id=<%= question.question_number %>>
        <%else %>
          <div id=<%= question.question_number %> style='display:none' >
        <% end %>
          <div class='pt-1 pb-2'>
            <span>
              <h6><b><%= question.question_number %>. <%= question.question_text %></b></h6>
            </span>
          </div>
          <% question.options_list.each_with_index do |option, index| %>
            <div>
              <% if question.child == nil %>
                <%= radio_button_tag "answers[#{question.question_number}]", option, false, data: { option_index: index }%>
              <%else %>
                <% if option == question.option_selected_to_display_child %>
                  <%= radio_button_tag "answers[#{question.question_number}]", option, false, data: { show_question: question.child, option_index: index } %>
                <%else %>
                  <%= radio_button_tag "answers[#{question.question_number}]", option, false, data: { hide_question: question.child, option_index: index } %>
                <% end %>
              <% end %>
              <%= label_tag "answers[#{question.question_number}][#{index}]", option %>
              <br>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <button id="submit-button" class="btn btn-secondary">Submit</button>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const submitButton = document.getElementById("submit-button");
    submitButton.addEventListener("click", function() {
      var answers_data = [];
      var completeSurvey = true;
      <% @questions.each do |question| %>

        var questionNumber = "<%= question.question_number %>";
        var optionDOM = document.querySelector('input[name="answers[<%= question.question_number %>]"]:checked');
        // console.log(optionDOM);

        check_req=false;
        if ("<%= question.parent_question_number %>" == ""){
          check_req=true;

        }else{

          var parent_show_quest=$(document.querySelector('input[name="answers[<%= question.parent_question_number %>]"]:checked')).data('showQuestion');

          if (parent_show_quest){
            console.log("child shown")
            check_req=true

          }else{
            console.log("child not shown")

          }
        }
        console.log(optionDOM);
        if (check_req){
          if (optionDOM === null) {
            console.log('Question not answered', questionNumber)
            completeSurvey = false;
            alert('Survey is not completed, please answer all questions');
            return;
          } else {
            console.log('some value was selected',questionNumber);
          }
        }else{
            console.log('check not req',questionNumber);
        }

        var option = $(optionDOM);
        var dataAttrs = option.data();
        var optionIndex = dataAttrs === undefined ? undefined : dataAttrs['optionIndex'];
        var optionValue = option.val();
        // console.log(optionValue, dataAttrs);
        answers_data.push([questionNumber, optionIndex]);

      <% end %>

      // console.log(answers_data);

      // send answers_data via ajax request

      var survey_id = <%= @survey.id %>;
      var user_id = <%= current_user.id %>;


      var csrftoken = $('meta[name=csrf-token]').attr('content');

      $.ajax({
        type: "POST",
        url: "/save_answers",
        data: {
          survey_id: survey_id,
          user_id: user_id,
          answers_data: answers_data,
          authenticity_token: csrftoken
        },
        success: function(response) {
          console.log("Responses saved successfully");
          alert('Responses saved successfully');
          window.location.href = "<%= survey_responses_path(@survey) %>";
        },
        error: function(xhr) {
          console.log("Error saving answers: " + xhr.statusText);
        }
      });
    });
  });

  $(document).ready(function() {
    $('input[type="radio"]').click(function() {
      var showQuestionAttr = $(this).data('showQuestion');
      var hideQuestionAttr = $(this).data('hideQuestion');

      if (showQuestionAttr) {
        $('#' + showQuestionAttr).show();
      } else if (hideQuestionAttr) {
        $('#' + hideQuestionAttr).hide();
        $('#' + hideQuestionAttr + ' input[type=radio]').prop('checked', false);
      }
    });
  });

</script>
<br>
  <%= link_to 'Back to Surveys', surveys_path %>
<br>

app/views/questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Questions</h1>

<div id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
    <p>
      <%= link_to "Show this question", question %>
    </p>
  <% end %>
</div>

<%= link_to "New question", new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>