config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'custom_post_form', to: 'custom_post_form#create', as: 'custom_post_form'
  resources :resources
  resources :local_resources
  resources :feedbacks
  post '/save_answers', to: 'responses#create', as: 'save_answers'
  resources :surveys do
    resources :responses
    member do
      get 'select_language'
    end
  end
  get 'get_questions/:survey_id/:language' , to: 'questions#get_questions', as: :get_questions
  resources :questions
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  root "home#index"

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  get '/show_all_responses', to: 'responses#show_all_responses'
  get '/feedback', to: 'resources#feedback'

  get '/getcounter', to: 'counter#get_counter'
  post '/increment', to: 'counter#increment_counter'
end

app/models/local_resource.rb
# class LocalResource < ApplicationRecord
#   validates :zip,:name,:website,:address, presence: true
#   geocoded_by :address
#   geocoded_by :zip
#   after_validation :geocode 

#   has_many :feedbacks, dependent: :destroy

#   def self.ransackable_associations(auth_object = nil)
#     [:feedbacks]
#   end

#   def self.ransackable_attributes(auth_object = nil)
#     ["address", "created_at", "email", "id", "name", "phone_number", "updated_at", "website", "zip", "latitude", "longitude", "is_partner"]
#   end

#   # after_validation :geocode, if: :address_changed?
# end

class LocalResource < ApplicationRecord
  validates :zip, :name, :website, :address, presence: true
  geocoded_by :address
  geocoded_by :zip
  after_validation :geocode 

  has_many :feedbacks, dependent: :destroy

  def self.ransackable_associations(auth_object = nil)
    ['feedbacks']
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "id", "name", "phone_number", "updated_at", "website", "zip", "latitude", "longitude", "is_partner"]
  end
end

app/controllers/local_resources_controller.rb
class LocalResourcesController < ApplicationController
  before_action :set_local_resource, only: %i[ show edit update destroy ]

  # GET /local_resources or /local_resources.json
  def index
    @local_resources = LocalResource.all
  end

  # GET /local_resources/1 or /local_resources/1.json
  def show
  end

  # GET /local_resources/new
  def new
    @local_resource = LocalResource.new
  end

  # GET /local_resources/1/edit
  def edit
  end

  # POST /local_resources or /local_resources.json
  def create
    @local_resource = LocalResource.new(local_resource_params)

    respond_to do |format|
      if @local_resource.save
        format.html { redirect_to local_resource_url(@local_resource), notice: "Local resource was successfully created." }
        format.json { render :show, status: :created, location: @local_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @local_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /local_resources/1 or /local_resources/1.json
  def update
    respond_to do |format|
      if @local_resource.update(local_resource_params)
        format.html { redirect_to local_resource_url(@local_resource), notice: "Local resource was successfully updated." }
        format.json { render :show, status: :ok, location: @local_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @local_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_resources/1 or /local_resources/1.json
  def destroy
    @local_resource.destroy

    respond_to do |format|
      format.html { redirect_to local_resources_url, notice: "Local resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local_resource
      debugger
      @local_resource = LocalResource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def local_resource_params
      params.require(:local_resource).permit(:name, :zip, :website, :address, :phone_number, :email, :is_partner)
    end
end

app/helpers/local_resources_helper.rb
module LocalResourcesHelper
end

app/views/local_resources/_form.html.erb
<%= form_with(model: local_resource) do |form| %>
  <% if local_resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(local_resource.errors.count, "error") %> prohibited this local_resource from being saved:</h2>

      <ul>
        <% local_resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/local_resources/_local_resource.html.erb
<div id="<%= dom_id local_resource %>">
  <p>
    <strong>Name:</strong>
    <%= local_resource.name %>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= local_resource.zip %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= local_resource.website %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= local_resource.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= local_resource.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= local_resource.email %>
  </p>

</div>

app/views/local_resources/edit.html.erb
<h1>Editing local resource</h1>

<%= render "form", local_resource: @local_resource %>

<br>

<div>
  <%= link_to "Show this local resource", @local_resource %> |
  <%= link_to "Back to local resources", local_resources_path %>
</div>

app/views/local_resources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Local resources</h1>

<%= link_to "New local resource", new_local_resource_path %>
<br/><br/>

<div id="local_resources">
  <% @local_resources.each do |local_resource| %>
    <%= render local_resource %>
    <p>
      <%= link_to "Show this local resource", local_resource %>
    </p>
  <% end %>
</div>

<%= link_to "New local resource", new_local_resource_path %>

app/views/local_resources/new.html.erb
<h1>New local resource</h1>

<%= render "form", local_resource: @local_resource %>

<br>

<div>
  <%= link_to "Back to local resources", local_resources_path %>
</div>

app/views/local_resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @local_resource %>

<div>
  <%= link_to "Edit this local resource", edit_local_resource_path(@local_resource) %> |
  <%= link_to "Back to local resources", local_resources_path %>

  <%= button_to "Destroy this local resource", @local_resource, method: :delete %>
</div>