config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'custom_post_form', to: 'custom_post_form#create', as: 'custom_post_form'
  resources :resources
  resources :local_resources
  resources :feedbacks
  post '/save_answers', to: 'responses#create', as: 'save_answers'
  resources :surveys do
    resources :responses
    member do
      get 'select_language'
    end
  end
  get 'get_questions/:survey_id/:language' , to: 'questions#get_questions', as: :get_questions
  resources :questions
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  root "home#index"

  get '/about_us', to: 'home#about_us'
  get '/contact_us', to: 'home#contact_us'
  get '/show_all_responses', to: 'responses#show_all_responses'
  get '/feedback', to: 'resources#feedback'

  get '/getcounter', to: 'counter#get_counter'
  post '/increment', to: 'counter#increment_counter'
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions
  has_many :responses

  def self.ransackable_associations(auth_object = nil)
    ["questions" , "responses"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "languages", "survey_category", "survey_name", "updated_at"]
  end
  accepts_nested_attributes_for :questions
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # # GET /surveys/new
  # def new
  #   @survey = Survey.new
  # end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  # def create
  #   @survey = Survey.new(survey_params)

  #   respond_to do |format|
  #     if @survey.save
  #       format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
  #       format.json { render :show, status: :created, location: @survey }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @survey.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  # def update
  #   respond_to do |format|
  #     if @survey.update(survey_params)
  #       format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
  #       format.json { render :show, status: :ok, location: @survey }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @survey.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /surveys/1 or /surveys/1.json
  # def destroy
  #   @survey.destroy

  #   respond_to do |format|
  #     format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  #select language
  def select_language
    @survey = Survey.find(params[:id])
    @languages = @survey.languages
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_survey
    #   @survey = Survey.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    # def survey_params
    #   params.fetch(:survey, {})
    # end



end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
</div>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Show this survey", @survey %> |
  <%= link_to "Back to surveys", surveys_path %>
</div>

app/views/surveys/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="surveys" class="container">
  <h1  class="style-colour text-center">Surveys</h1>
  <br>
  <table class="table table-light table-borderless">
    <thead class="thead-light">
      <tr>
        <th scope="col">Survey Name</th>
        <th scope="col">Survey Category</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <td><%= survey.survey_name %></td>
          <td><%= survey.survey_category %></td>
          <td><%= link_to "Take Survey", select_language_survey_path(survey) %></td>
          <td><%= link_to "Recent Response", survey_responses_path(survey) %></td>
          <td><%= link_to "See All Responses", show_all_responses_path(survey_id: survey.id) %></td>
          <td><%= link_to "See Resources", resources_path(category: survey.survey_category) %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Back to surveys", surveys_path %>
</div>

app/views/surveys/select_language.html.erb
<title>Select Language</title>

<div class="list-1">
  <h1 class="mb-4 style-colour">Select Language</h1>

  <ul class="list-group">
    <% @languages.each do |language| %>
      <li class="text-black mb-2">
        <%= link_to language, get_questions_path(survey_id: @survey.id, language: language), class: "text-black" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/surveys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey %>

<div>
  <%= link_to "Edit this survey", edit_survey_path(@survey) %> |
  <%= link_to "Back to surveys", surveys_path %>

  <%= button_to "Destroy this survey", @survey, method: :delete %>
</div>